"""fix error

Revision ID: 607809881c67
Revises: 
Create Date: 2025-07-09 17:44:34.609008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607809881c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_insurance_user_id', ['user_id'])
        batch_op.create_unique_constraint('uq_insurance_vehicle_id', ['vehicle_id'])
        batch_op.create_foreign_key('fk_insurance_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_insurance_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_insurance_vehicle_id', type_='unique')
        batch_op.drop_constraint('uq_insurance_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
