"""fix error

Revision ID: 88c4e172ace6
Revises: 607809881c67
Create Date: 2025-07-09 18:12:46.412527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c4e172ace6'
down_revision = '607809881c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_insurance_user_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_insurance_vehicle_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_insurance_vehicle_id'), ['vehicle_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_insurance_user_id'), ['user_id'])

    # ### end Alembic commands ###
